# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Farm+Cellar
email: hello@farmandcellar.com
description: "Farm+Cellar is a video production agency that specializes in food and wine."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.farmandcellar.com/"
twitter_username: farmandcellar
github_username:

# Build settings
markdown: kramdown
